export const englishCopy = {
    "header": {
        "projects": "Projects",
        "experience": "Experience",
        "about": "About",
        "lang": "FR"
    },
    "home": {
        "heading": "Hey there, I'm Cyrielle",
        "subheading": "Front End Developer, Project Manager, Problem solving enthousiast.",
        "desc": "Just graduated from the Web Developer course on OpenClassrooms, I'm looking for my first experience as a Front End Developer.",
        "about1": "Tech enthusiast",
        "about2": ", I've been working at tech start ups for 10 years. I worked in Client Support for a few years while teaching myself UX and Developement basics.",
        "about3": "I'm just getting out of a ",
        "about4": "Web Developer course",
        "about5": " and I'm looking for tech projects",
        "about6": "I'm passionate about ",
        "about7": "problem solving", 
        "about8": " and improving the user experience 🙌",
        "contact": "If you’d like to discuss a project or just have a chat, feel free to reach out!",
        "contactcta": "Contact"
    },
    "resume": {
        "experience": "Experience",
        "training": "Training",
        "skills": "Skills",
        "oc2": "Knowledge Management Specialist",
        "oc2date": "oct 2022 - present",
        "oc2item1": "Managing the knowledge for the entire Ops team",
        "oc2item2": "Creating guidelines and maintening our Help Centers",
        "oc2item3": "Tracking our success metrics (content quality, impact, ...)",
        "oc1": "Mentor & Coach Support Manager",
        "oc1date": "july 2019 - sep 2022",
        "oc1item1": "Creating the Mentor & Coach Support processes",
        "oc1item2": "Creating the guidelines for our Help Centers",
        "oc1item3": "Organizing and updating our Help Centres (student, mentor, employer)",
        "drivy": "Client Support Project Manager",
        "drivydate": "jan 2018 - june 2019",
        "drivyitem1": "Writing and updating the Help Center across 6 countries",
        "drivyitem2": "Passing on the user feedback via an internal newsletter",
        "drivyitem3": "Reshaping our macro system and writing it across 6 countries ",
        "schibsted": "Customer Success Manager (London)",
        "schibsteddate": "march 2016 - dec 2017",
        "schibsteditem1": "Launching the Client Service team (procedures, training)",
        "schibsteditem2": "Gathering user feedback and suggestions for Product & UX improvements",
        "schibsteditem3": "Analysing user behaviour on several projects using webanalytics and user testing to improve UX",
        "lbc": "Process and Prod Officer",
        "lbcdate": "oct 2012 - feb 2016",
        "lbcitem1": "Answering user questions (Level 2)",
        "lbcitem2": "Sending and analysing NPS surveys",
        "lbcitem3": "Procedure writing to improve our answer quality (from 78% to 92%)",
        "download": "Download my resume"
    }
}