export const englishCopy = {
    "header": {
        "projects": "Projects",
        "experience": "Experience",
        "about": "About",
        "lang": "FR"
    },
    "home": {
        "heading": "Hey there, I'm ",
        "subheading": "Front End Developer, I like building experiences for the web",
        "desc": "Just graduated from the Web Developer training program on OpenClassrooms, I'm looking for my first experience as a Front End Developer.",
        "about1": "Tech enthusiast",
        "about2": ", I've been working at tech start ups for 10 years. I'm just getting out of a Web Developer course and I'm looking for tech projects.",
        "about3": "I like",
        "about4": "💪 Working on challenging projects",
        "about5": "👩‍🏫 Learning new things",
        "about6": "⭐️ Improving the user experience",
        "about7": "🧩 Solving problems",
        "about8": "... ⚽️ Football",
        "about9": "I dislike",
        "about10": "😴 Being bored",
        "about11": "👸 Political games",
        "about12": "🤫 Dishonesty",
        "about13": "... 😱 Scary movies",
        "contact": "If you’d like to discuss a project, feel free to reach out!",
        "contactcta": "Contact"
    },
    "mainheader": {
        "projects": "Projects",
        "experience": "Experience",
        "about": "About",
        "contact": "Contact"
    },
    "projects": {
        "kanap": "Integrating the Kanap website with Javascript. Getting the data from the API, creating a functioning cart with local storage, and sending the user's order to the server.",
        "kasa": "Integrating the Kasa website with React. Using states, componants and uploading the website on Github pages.",
        "ohmyfood": "Integrating the Ohmyfood! website in HTML and with SASS. Using CSS animations (transitions and keyframes).",
        "airpeger": "Creating the Airpeger website. Integrating in React, creating the server side with Node.js (user accounts, user information, ...), and hosting the app (OVH / Vercel)."
    },
    "resume": {
        "experience": "Experience",
        "training": "Training",
        "skills": "Skills",
        "oc2": "Knowledge Management Specialist",
        "oc2date": "oct 2022 - present",
        "oc2item1": "Managing the knowledge for the entire Ops team",
        "oc2item2": "Customizing our Help Center theme (HTML/CSS)",
        "oc2item3": "Defining and tracking our success metrics (content quality, impact, ...)",
        "oc1": "Mentor & Coach Support Manager",
        "oc1date": "july 2019 - sep 2022",
        "oc1item1": "Creating the Mentor & Coach Support processes",
        "oc1item2": "Creating our custom contact page (HTML/CSS/JS)",
        "oc1item3": "Organizing and updating our Help Centres (student, mentor, employer)",
        "drivy": "Client Support Project Manager",
        "drivydate": "jan 2018 - june 2019",
        "drivyitem1": "Writing and updating the Help Center across 6 countries",
        "drivyitem2": "Passing on the user feedback via an internal newsletter",
        "drivyitem3": "Reshaping our macro system and writing it across 6 countries ",
        "schibsted": "Customer Success Manager (London)",
        "schibsteddate": "march 2016 - dec 2017",
        "schibsteditem1": "Launching the Client Service team (procedures, training)",
        "schibsteditem2": "Gathering user feedback and suggestions for Product & UX improvements",
        "schibsteditem3": "Analysing user behaviour on several projects using webanalytics and user testing to improve UX",
        "lbc": "Process and Prod Officer",
        "lbcdate": "oct 2012 - feb 2016",
        "lbcitem1": "Answering user questions (Level 2)",
        "lbcitem2": "Sending and analysing NPS surveys",
        "lbcitem3": "Procedure writing to improve our answer quality (from 78% to 92%)",
        "download": "Download my resume"
    }
}