export const frenchCopy = {
    "header": {
        "projects": "Projets",
        "experience": "Expérience",
        "about": "A propos",
        "lang": "EN"
    },
    "home": {
        "heading": "J'me présente, je m'appelle Cyrielle",
        "subheading": "Développeur Front-End, Project Manager, Amatrice de problèmes à résoudre.",
        "desc": "Diplômée de la formation Développeur Web OpenClassrooms, je suis à la recherche de mon premier poste en tant que Développeur Front-End.",
        "about1": "Passionnée de technologie",
        "about2": ", je travaille dans le monde du web depuis 10 ans. J'ai travaillé au Support Client pendant plusieurs années tout en apprenant les bases du développement et de l'UX dans mon temps libre.",
        "about3": "Aujourd'hui, je sors d'une ",
        "about4": "formation de Développeur Web",
        "about5": " et je cherche des projets de développement.",
        "about6": "J'aime ",
        "about7": "résoudre des problèmes", 
        "about8": " et améliorer l'expérience utilisateur 🙌",
        "contact": "Si vous voulez parler d'un projet, ou juste discuter, n'hésitez pas à me contacter !",
        "contactcta": "Me contacter"
    },
    "resume": {
        "experience": "Expérience",
        "training": "Formation",
        "skills": "Compétences",
        "oc2": "Knowledge Management Specialist",
        "oc2date": "oct 2022 - aujourd'hui",
        "oc2item1": "Gestion de la connaissance pour toute l'équipe Opérations",
        "oc2item2": "Définition des guidelines et maintenance des Centre d'Aide",
        "oc2item3": "Suivi des indicateurs (qualité, impact, ...)",
        "oc1": "Mentor & Coach Support Manager",
        "oc1date": "juil 2019 - sep 2022",
        "oc1item1": "Mise en place des process du Support mentorat et coaching",
        "oc1item2": "Rédaction des consignes pour le contenu de notre centre d'aide",
        "oc1item3": "Aide à la mise en place des centres d’aide (étudiants, mentor, employeur)",
        "drivy": "Chef de Projet Service Client",
        "drivydate": "jan 2018 - juin 2019",
        "drivyitem1": "Rédaction et mise à jour du Help Center (6 pays)",
        "drivyitem2": "Remontée des retours utilisateurs via une newsletter interne",
        "drivyitem3": "Refonte et rédaction du système de macros (6 pays)",
        "schibsted": "Customer Success Manager (Londres)",
        "schibsteddate": "mars 2016 - dec 2017",
        "schibsteditem1": "Lancement de l'équipe Support client (procédure, formation)",
        "schibsteditem2": "Remontée des demandes et suggestions utilisateurs",
        "schibsteditem3": "Analyse des comportements utilisateurs sur plusieurs produits (web analytics & user testing) pour recommandations produit",
        "lbc": "Chargée de prod et process Relation Client",
        "lbcdate": "oct 2012 - fév 2016",
        "lbcitem1": "Traitement des demandes utilisateurs (Niveau 2)",
        "lbcitem2": "Envoi et analyse d'enquêtes de satisfaction pour améliorer notre NPS",
        "lbcitem3": "Rédaction de procédure pour améliorer la qualité de l’équipe (de 78% à 92%)",
        "download": "Télécharger mon CV"
    }
}